if(WIN32)
    add_executable(component_gallery WIN32 component_gallery.cpp)
    add_executable(layout_demo WIN32 layout_demo.cpp)
else()
    add_executable(component_gallery component_gallery.cpp)
    add_executable(layout_demo layout_demo.cpp)
endif()

target_link_libraries(component_gallery PRIVATE AsterUI Qt${QT_VERSION_MAJOR}::Widgets)
target_link_libraries(layout_demo PRIVATE AsterUI Qt${QT_VERSION_MAJOR}::Widgets)
