if(WIN32)
    add_executable(ComponentGallery WIN32 ComponentGallery.cpp)
    add_executable(LayoutDemo WIN32 LayoutDemo.cpp)
else()
    add_executable(ComponentGallery ComponentGallery.cpp)
    add_executable(LayoutDemo LayoutDemo.cpp)
endif()

target_link_libraries(ComponentGallery PRIVATE AsterFlorets Qt${QT_VERSION_MAJOR}::Widgets)
target_link_libraries(LayoutDemo PRIVATE AsterFlorets Qt${QT_VERSION_MAJOR}::Widgets)
